= README
Katie Tothill <ktothill@gmail.com>
:description: README
:revdate: June 9, 2022
:url-repo: https://github.com/ktothill
:sectnums!:
:toc:
:doctype: book
:text-align: left

= introduction
My samples include upstream and downstream technical writing samples formatted in asciidoc.

They are original and were researched using primary sources (e.g.: ownCloud's offical documentation). I wrote the case studies based on my experiences as a Technical Analyst and Customer Success Engineer.

The ownCloud code was sourced directly from their official documentation, but I condensed some of their code to combine steps (e.g.: Step 2 in Section 1.2.3 is written as a single command for efficiency). I wrote all of the other code samples and scripts from scratch.

The samples were written using the IBM Style Guide and the Red Hat Supplementary Style Guide. No one else edited the content. These documents are separate from my current work product and are not part of a larger documentation set.

== ownCloud Server Quick Start Guide
Downstream samples instruct users to install and configure an ownCloud server.

== Technical Writing Samples
Upstream samples are intended for Domain Name System (DNS) engineers and support analysts. Downstream samples are intended for users that have DNS service with the fictional company, “OurDNS”.

These documents do not define best practices for any type of documentation.

Composed in Visual Studio Code v1.67.2
